using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShoeHouse.Data
{
    /// <summary>
    /// Metadata to add annotations in Article without modify the autogenerated code.
    /// </summary>
    class ArticleMetadata
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Display(Name = "Total in shelf")]
        public int TotalInShelf { get; set; }

        [Display(Name = "Total in vault")]
        public int TotalInVault { get; set; }

        [Display(Name = "Store")]
        public int StoreId { get; set; }
    }

    [MetadataType(typeof(ArticleMetadata))]
    public partial class Article
    {
    }
}
