using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShoeHouse.Data
{
    /// <summary>
    /// Metadata to add annotations in Store without modify the autogenerated code.
    /// </summary>
    class StoreMetadata
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string Address { get; set; }
    }

    [MetadataType(typeof(StoreMetadata))]
    public partial class Store
    {
    }
}
